### ISSUE TITLE
db:create hangs with mongodb

### ISSUE THREAD

**Issue by zontafil** [BlueHotDog/sails-migrations#40]
db:create hangs with:

```
  grunt db:create
  Running "db:loadConfig" task

  Running "db:createInternalTask" task
  Trying to create a new database
```

verbose mode doesn't show additional info

**Comment by sgnn7** [comment]
@BlueHotDog I know this is a closed issue but even MongoDB sometimes requires migrations, especially in cases of changing existing attributes for records or pushing pre-canned data into it (i.e some predefined users). Depending on my time commitment, I might look into this if you guys don't mind having that logic in the codebase.

**Comment by BlueHotDog** [comment]
@sgnn7 sounds logical, please keep in mind that i dont have the time to maintain this project,
I'll be happy to review the code etc.

**Comment by sgnn7** [comment]
@BlueHotDog Fair enough - makes sense to me :)
