### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by magmel48** [BlueHotDog/sails-migrations#48]
Please, provide a few examples of usage of your plugin. Link in README file is outdated

**Comment by jaydev** [comment]
+1

It's hard to understand at a glance what advantages sails-migrations provides over using knex alone.

**Comment by KirillSuhodolov** [comment]
+1

**Comment by BlueHotDog** [comment]
Hey guys, crazy time here, we're planning to do this during this Saturday

**Comment by BlueHotDog** [comment]
Added, please LMK if that's what you need or you need something more explicit.
