### ISSUE TITLE
Migration succeeds but I receive an error

### ISSUE THREAD

**Issue by kevinob11** [BlueHotDog/sails-migrations#54]
When I attempt to migrate it succeeds in creating my table but outputs an error at the command line. The error and the code for my migration are below.

## error
```
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at SchemaBuilder_PG.Target.then (../node_modules/sails-migrations/node_modules/knex/lib/interface.js:27:33)
```

## migration
```javascript
'use strict';

exports.up = function(knex, Promise) {
  return knex.schema.createTable('user', function (table) {
  	table.increments();
	  table.datetime('createdAt');
	  table.datetime('updatedAt');
	})
};

exports.down = function(knex, Promise) {
  return knex.schema.dropTable('user');
};
```

**Comment by BlueHotDog** [comment]
Hi Kavin, thanks for the report, will take a look(and fix) during the
weekend :)

You're more then welcome to also try and fix and submit a PR :) (we dont
bite)

**Comment by kevinob11** [comment]
I'm happy to give it a shot, I'll carve out some time Friday to take a look.

**Comment by kevinob11** [comment]
I found a bit of time for this tonight, but I'm honestly not quite sure how to parse what I'm finding as of yet. I'll plan on dedicating some more time on this Friday and this weekend, I'd really like to help! Also below is the full stack trace of the error instead of the two lines I gave you above.

```
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at SchemaBuilder_PG.Target.then (/Users/kevin/code/fikes/api/node_modules/sails-migrations/node_modules/knex/lib/interface.js:30:33)
    at SchemaBuilder_PG.Target.(anonymous function) [as bind] (/Users/kevin/code/fikes/api/node_modules/sails-migrations/node_modules/knex/lib/interface.js:76:21)
    at Migrator_PG.<anonymous> (/Users/kevin/code/fikes/api/node_modules/sails-migrations/node_modules/knex/lib/migrate/index.js:121:6)
From previous event:
    at Migrator_PG.<anonymous> (/Users/kevin/code/fikes/api/node_modules/sails-migrations/node_modules/knex/lib/migrate/index.js:166:15)
From previous event:
    at Migrator_PG.Migrator._migrationData (/Users/kevin/code/fikes/api/node_modules/sails-migrations/node_modules/knex/lib/migrate/index.js:182:10)
    at Migrator_PG.<anonymous> (/Users/kevin/code/fikes/api/node_modules/sails-migrations/node_modules/knex/lib/migrate/index.js:50:15)
From previous event:
    at /Users/kevin/code/fikes/api/node_modules/sails-migrations/lib/sails-migrations/migrate_to_latest.js:12:23
    at process._tickCallback (node.js:442:13)
```

**Comment by BlueHotDog** [comment]
Hi Kavin, i dont see anything wrong with your code,
is there a chance to take a look at the actual code?

**Comment by kevinob11** [comment]
Absolutely. Here is a repo in which I can successfully re-create the error by running "sails-migrations migrate". It's a brand new sails app with only database config, model config to turn off auto-migrations and a user api to match the user table migration I made.

https://github.com/kevinob11/sails-migrations-test

**Comment by BlueHotDog** [comment]
Amazing, will check tomorrow!

**Comment by kevinob11** [comment]
Thanks! I'm happy to move this to another issue or non-github convo, but is the goal of this project in the long term to be able to auto generate migrations from model definitions in sails?

**Comment by BlueHotDog** [comment]
the short answer is: no :)
the longer one is:
quite the contrary, you want your migrations to NEVER touch your models.
since models are committed via your source control, but your database/data isnt
the purpose of the migrations is to bring your database to the state you want it to be, through atomic operations, sometime this includes very complex transformations.(data migrations is only one of those)
so you want the operations to execute in the "exact" same order your wrote them.

It's *not* the purpose of db migrations to "keep the db in sync" with your models. 
just think how scary is that with real, live data. imagine you drop a column with real data just because you removed it from the model.. really scary.

**Comment by kevinob11** [comment]
Yeah I get exactly what you mean, I would _never_ expect migrations to do that and I see how that would be really scary with any live app.

What I had in mind though was more of a convenience feature. Not something you would use as the standard method of making database changes, more a one time use at the beginning of a project in order to reduce how much code you have to write. I picture it as: I build all of my models in sails, I then run "sails-migrations generate:model user", at which point sails-migrations generates a migration file that matches what you have in your user model, so you would still have a history of database changes in the migrations file, but you don't have to manually write it. You should of course check that file, and you would never use this feature for additional changes to a model, just the initial build of it. Seems like it would save some time and help beginners make the change to a migration tool rather than rely on sails auto migrations, which always seem like a dangerous "magical" feature to me.

If the answer is that this introduces a lot of danger and confusion for something that adds only a little convenience, I get it. It just seemed like something that might be valuable.

One more question that doesn't belong in this issue thread: Besides pulling connector config from Sails what additional features does this project add above and beyond just using knex to handle your migrations? To be clear, I think that is plenty worthwhile, I was just considering making the switch and I want to make sure I'm making an informed decision.

Thanks!

**Comment by BlueHotDog** [comment]
regarding point no.1: seems like a nice feature, but involves quite a lot of debugging, i'm extremely busy currently, but please open a new issue with this feature so we can think and discuss this further. maybe i'll find one weekend to do this.

regarding point no.2: you're right, this is just a small npm that does about that :) although stuff will be added i guess. but the intention is just for this to be a glue between 2 good modules.

**Comment by kevinob11** [comment]
Great! I'll get a new issue opened this week, and I'd be happy to help work on it as well!

**Comment by JetFault** [comment]
+1, having same issue.

The sails_migrations table gets created, but none of the migrations are run

**Comment by kevinob11** [comment]
Not quite the same issue, as for me the migrations were properly run. 

@BlueHotDog my apologies for not getting the new issue opened last week, I'm definitely still interested I'll make sure I don't lose track of it.

**Comment by JetFault** [comment]
@kevinob11 i edited my issue. migrations were being done. so same issue

**Comment by kevinob11** [comment]
Ah missed the edit. Right-o then! Love to hear what you may be able to find. I had trouble tracking this down. Its a then on a promise deep in knex that is being called by sails-migrations without any params, I think.

**Comment by Enkows** [comment]
knex@0.7.4 fixed this issue.

**Comment by kevinob11** [comment]
Great!
