### ISSUE TITLE
Support for sails v0.11

### ISSUE THREAD

**Issue by tibotiber** [BlueHotDog/sails-migrations#64]
Hi! I'm trying to use this with sails v0.11. I've done really basic stuff so far without any problem. Do you know of any issue that may arise later on? Is the README to be updated (it indicates support up to 0.10.5)? Not sure whether the v0.10 to v0.11 upgrade has affected any of the aspects this lib relies on...

**Comment by JHereu** [comment]
:+1:

**Comment by TylerBre** [comment]
Does not support v0.11

```
sails-migrations status              
path.js:488
      throw new TypeError('Arguments to path.join must be strings');
            ^
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:488:13)
  at Function.SailsIntegration.getSailsConfig 
```

etc.

looks like the adapter can't get the sailsConfig, and it looks like versions are hardcoded

I would love to submit a pr, but I have no idea how to dev on this. Running the tests just spits out npm errors??

**Comment by sortegam** [comment]
+1

**Comment by RWOverdijk** [comment]
:+1:

**Comment by BlueHotDog** [comment]
Hi guys, unfortunately i do not have any capacity to look into this issue right now,
any PRs are welcome.

**Comment by niallobrien** [comment]
Has anyone isolated the issue?

**Comment by joaosa** [comment]
I submitted a PR that addresses this :)

**Comment by BlueHotDog** [comment]
merged, will push a new version later on.





On Thu, Oct 29, 2015 at 8:47 AM João Sousa Andrade <notifications@github.com>
wrote:
I submitted a PR that addresses this :)

**Comment by RWOverdijk** [comment]
awesome!

**Comment by joaosa** [comment]
I have a production build depending on this. Is there any chance you could make the release? :)

**Comment by BlueHotDog** [comment]
@joaosa published.
