### ISSUE TITLE
Helping maintain this module

### ISSUE THREAD

**Issue by mikermcneil** [BlueHotDog/sails-migrations#74]
@BlueHotDog Danni, as you probably remember, we're using sails-migrations in production at Treeline.  I think we still need to find someone who can help push the project further forward (e.g. as far as documentation), but I'd like to offer to help if we can in the mean time in the case of any immediate term emergencies or bugs that come up.

I'd also like to see manual migrations make their way into the Sails core CLI in the future.  This would need to be specced out further into a proper proposal, and I think the first step to getting there is for more folks to start using this module (hopefully incorporating ideas from [sails-db-migrate](https://github.com/building5/sails-db-migrate)).

So in the mean time, please feel free to ping any of the Sails core team on Twitter for any high-priority patches in sails-migrations and we'll do our best to help.  Thanks everyone!

**Comment by RWOverdijk** [comment]
@mikermcneil I'm also here :)

**Comment by mikermcneil** [comment]
@RWOverdijk :+1:

**Comment by joaosa** [comment]
@BlueHotDog PR #76 might be of interested for Sails 0.12 and Node 6.1

**Comment by sudrao** [comment]
@BlueHotDog This project has not been published to npm in a long time. Can it please be released? https://www.npmjs.com/package/sails-migrations says the last publish was 9 months ago.

**Comment by RWOverdijk** [comment]
@BlueHotDog It's not possible for me to release. Merging and reviewing is ok though. If you could add me, that'd be great. <insert meme>

Pretty sure we can close this issue, seeing how there are contributors now. :)
