### ISSUE TITLE
Not working in Node 6

### ISSUE THREAD

**Issue by syaau** [BlueHotDog/sails-migrations#77]
Path is 'null' while running sails-migrations in Node 6

**Comment by joaosa** [comment]
@syaau This PR should fix the issue https://github.com/BlueHotDog/sails-migrations/pull/76

**Comment by joaosa** [comment]
@syaau This should be fixed in 2.0.9

**Comment by RWOverdijk** [comment]
Tested and confirmed. If this issue still persists for anyone else, please leave a comment with your exact node version and OS version.
