### ISSUE TITLE
bump knex version to support .ts migrations

### ISSUE THREAD

**Issue by mychalvlcek** [BlueHotDog/sails-migrations#81]
it would be great to bump up version of knex lib to support typescript migration files

**Comment by joaosa** [comment]
@mychalvlcek 

I bumped knex to 0.13.0 (0.12.7 was the minimum to support typescript migration files). Let me know if it's working fine for you :)

**Comment by mychalvlcek** [comment]
@joaosa thanks a lot, works as espected!
